export const BUILDING_MAP_ZONE_UI_CONSTANTS = {
    ACTION_INSET: 4,
    ACTION_SIZE: 24,
    ACTION_GAP: 4,
    ACTIONS_COUNT: 3,
    TITLE_HEIGHT: 26,
    TITLE_GAP: 8,
    COMPACT_ZONE_HEIGHT: 84,
    DEFAULT_ACTION_TOP_REFERENCE: 72,
    DEFAULT_TITLE_CENTER_REFERENCE: 48,
    MAX_ACTION_TOP_OFFSET: 28,
    MAX_TITLE_OFFSET: 34
} as const
