export const BUILDING_MAP_VIEWPORT_CONSTANTS = {
    DEFAULT_UNIT_SIZE: 36,
    MIN_UNIT_SIZE: 6,
    MAX_UNIT_SIZE: 10000,
    ZOOM_SENSITIVITY: 0.0025,
    ZOOM_BUTTON_FACTOR: 1.35,
    PAGE_LIMIT: 200,
    MAX_AUTO_PAGES: 2,
    DEFAULT_PAN_X: 16,
    DEFAULT_PAN_Y: 16,
    VIEWPORT_SYNC_DELAY_MS: 250,
    ADD_HANDLE_REENABLE_DELAY_MS: 180,
    FOCUS_SCALE: 0.58
} as const
