export const BUILDING_MAP_HOVER_CONSTANTS = {
    ADD_HANDLE_COORDINATE_UPDATE_THRESHOLD: 0.25,
    ADD_HANDLE_EDGE_SNAP_TOLERANCE: 0.5,
    ADD_HANDLE_EDGE_GAP: 1,
    ADD_HANDLE_DEPTH: 1
} as const
