export const LENGTH = {
    MAX_EMAIL_LENGTH: 100,
    MAX_PASSWORD_LENGTH: 100,
    MAX_SEARCH_LENGTH: 100,
    MAX_NAME_LENGTH: 100,
    MAX_ZONE_TITLE_LENGTH: 100,
    MAX_PHONE_LENGTH: 50,
    MAX_ORGANIZATION_TITLE_LENGTH: 100,
    MAX_BUILDING_TITLE_LENGTH: 100,
    MAX_ADDRESS_LENGTH: 250,
    MAX_DESCRIPTION_LENGTH: 500,
}
